CREATE TABLE game_types (
    id SERIAL PRIMARY KEY,
    type_name VARCHAR(100) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    bonus NUMERIC(10, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
