CREATE TABLE cards (
    id SERIAL PRIMARY KEY,
    card_sn VARCHAR(100) UNIQUE NOT NULL,
    data TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
