services:
  nats-server-1:
    image: nats:latest
    ports:
      - "4222:4222"
    networks: 
      - natsnet

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin4
    image: 'dpage/pgadmin4'
    ports:
      - "51051:80"
    restart: always
    env_file:
      - ./.env
volumes:
  postgres:
networks:
  natsnet:
    name: natsnet